### ISSUE TITLE
Orchestration - Node Based Licensing

### ISSUE THREAD

**Issue by jonathonbarton** [jacebenson/snkilled#2]
Killed 2018. 
Replaced with **Orchestration - Transaction Based Licensing** which 'charges' for each transaction that is orchestrated. 
2017 Orchestration - 10000 AD updates per month = 1 Node license use.
2018 Orchestration - 10000 AD updates per month = 10,000 Transactions = $80,000 (rumored pricing)

**Comment by jacebenson** [comment]
Do you kno when Orchestration started... like in general?

**Comment by jacebenson** [comment]
Found it.  Fall 2010 release.
