### ISSUE TITLE
Processor

### ISSUE THREAD

**Issue by iamkalai** [jacebenson/snkilled#3]
- What is being killed: Processor
- When was it first added to ServiceNow: Pre-Aspen
- When was it removed, or replaced: NewYork
- If it was replaced, with what: Scripted Rest API
- Any Additional Comments: While legacy, custom processors will continue to be supported, creating new custom processors has been deprecated. Instead, please use the Scripted REST APIs.

**Comment by iamkalai** [comment]
I could only find the deprecation comment in NewYork version docs only - https://docs.servicenow.com/bundle/newyork-application-development/page/script/processors/concept/c_Processors.html
So, I have stated deprecation as NewYork.

**Comment by jacebenson** [comment]
Added
