### ISSUE TITLE
Application Creator

### ISSUE THREAD

**Issue by iamkalai** [jacebenson/snkilled#4]
- What is being killed: Application Creator
- When was it first added to ServiceNow: Fuji
- When was it removed, or replaced: Replaced. 
- If it was replaced, with what: Guided Application Creator
- Any Additional Comments: There is no migration path from the legacy application creator to Guided Application Creator. You can add a property to force legacy application creator to open instead of Guided Application Creator. For more information, see [Activate the legacy application creator](https://docs.servicenow.com/bundle/newyork-application-development/page/build/applications/task/activate-legacy-app-creator.html).

**Comment by jacebenson** [comment]
Do oyu know when it was replaced?

**Comment by iamkalai** [comment]
This was replaced in Newyork - https://docs.servicenow.com/bundle/newyork-application-development/page/build/applications/concept/c_ApplicationCreationOptions.html

**Comment by jacebenson** [comment]
Added
