### ISSUE TITLE
Execution Plans

### ISSUE THREAD

**Issue by JoeEmployee** [jacebenson/snkilled#5]
Question                                                  | Answer 
--------------------------------------- | -------
What is being killed                                 | Execution Plans
When was it first added to ServiceNow  | 2002
**When** was it removed, or replaced   | N/A
If it was replaced, with what                    | Workflow
Proposed State                                        | Dead

## Any Additional Comments
This is really a legacy feature that is still around and I'm sure some people use it, but I can't imagine it has any support.

**Comment by jacebenson** [comment]
I added as Life Support, as it can be used, but has a clearly better solution weather that's workflow, or flow designer.
