### ISSUE TITLE
GlideSystem SQL

### ISSUE THREAD

**Issue by snamjosh** [jacebenson/snkilled#6]
Question                                                  | Answer 
--------------------------------------- | -------
What is being killed                                 | GS SQL
When was it first added to ServiceNow  | Aspen
**When** was it removed, or replaced   | Geneva
If it was replaced, with what                    | GlideRecord API
Proposed State                                        | Dead

When truncating table, gs.sql orphans records and causes data corruption. That is the main reason it was dangerous.

**Comment by jacebenson** [comment]
Thanks for this.  Adding it now.

**Comment by jacebenson** [comment]
Added.
